source 'https://rubygems.org'

ruby '3.2.4'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Enumerize
gem 'enumerize'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Bootstrap
gem 'bootstrap', '~> 5.3.3'
gem 'dartsass-sprockets'
gem 'jquery-rails'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Tried installing render
gem 'render', '~> 0.1.2'

group :development, :test do
  # Debugging tools
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot', '~> 6.4'
  gem 'factory_bot_rails'
  gem 'letter_opener'
  gem 'letter_opener_web', '~> 3.0'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 6.0'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
end

# Authentication
gem 'devise', '~> 4.9'

# Pagination
gem 'pagy', '~> 8.6'

# Data creation for testing
gem 'faker'

# Dynamic permissions
gem 'pundit'

# Image uploading
gem 'shrine', '~> 3.6'

# Interface admin
gem 'activeadmin'

# Plus integrations with:
gem 'cancancan'
gem 'draper'


gem 'simplecov', require: false, group: :test
